# =============================================================================
# BitCounting - Build & Release Workflow
# =============================================================================
# This workflow builds the app for all platforms when you create a new release tag

name: Build & Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-action@stable

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'BitCounting ${{ github.ref_name }}'
          releaseBody: |
            ## What's New
            See [CHANGELOG.md](https://github.com/Sat-Stone/BitCounting/blob/main/CHANGELOG.md) for details.
            
            ## Installation
            
            ### macOS
            1. Download `BitCounting_x.x.x_aarch64.dmg` (Apple Silicon) or `BitCounting_x.x.x_x64.dmg` (Intel)
            2. Open the `.dmg` and drag BitCounting to Applications
            3. First launch: Right-click → Open → Click "Open"
            
            ### Security Note
            This app is not signed with an Apple Developer certificate. macOS will show a warning on first launch. This is normal for open-source apps distributed outside the App Store.
          releaseDraft: true
          prerelease: false

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-action@stable

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'BitCounting ${{ github.ref_name }}'
          releaseDraft: true
          prerelease: false

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-action@stable

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'BitCounting ${{ github.ref_name }}'
          releaseDraft: true
          prerelease: false